[package]
name = "gitbucket"
version = "0.1.0"
authors = ["Vladimir Burdukov <chippcheg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitbucket = { path = "../bitbucket" }
http_client = { path = "../http_client" }

futures-executor = "0.3"

git2 = { version = "0.10" }

url = "2.0"
regex = "1.3"
