[package]
name = "gitbucket"
version = "0.1.0"
authors = ["Vladimir Burdukov <chippcheg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitbucket = { path = "../bitbucket" }
git2 = { version = "0.10", features = [] }
url = "2.0"
dirs = "2.0"
regex = "1.3"
